// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lastonebd.Data;

#nullable disable

namespace lastonebd.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lastonebd.Data.iSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("iSections");
                });

            modelBuilder.Entity("lastonebd.Data.iWorkers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Surname")
                        .HasColumnType("int");

                    b.Property<int>("iSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("iSectionId");

                    b.ToTable("iWorkersTab");
                });

            modelBuilder.Entity("lastonebd.Data.iWorkers", b =>
                {
                    b.HasOne("lastonebd.Data.iSection", "iSection")
                        .WithMany("iWorkersTab")
                        .HasForeignKey("iSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("iSection");
                });

            modelBuilder.Entity("lastonebd.Data.iSection", b =>
                {
                    b.Navigation("iWorkersTab");
                });
#pragma warning restore 612, 618
        }
    }
}
